server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/multi-module-project/cloud-config-repo
#        native:
#          search-locations: file:C:/git-local-repo
