server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/multi-module-project/cloud-config-repo
          default-label: master
        native:
          search-locations: file:C:/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

